spring.application.name=realestate

# PostgreSQL Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/nexus_db
spring.datasource.username=postgres
spring.datasource.password=GPanos@2005
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2

# Hibernate (JPA) Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=true

# JWT Secret
jwt.secret=9a4f434556513571537638792F423F4528482B4D6251655468576D5A71347437